version: '3'

services:
  server:
    image: nginx
    volumes:
      - ./:/var/www
    ports:
      - 7000:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80